### ISSUE TITLE
Db content isn't cleared between each test

### ISSUE THREAD

**Issue by Aerion** [Giorgi/EntityFramework.Exceptions#16]
Steps to reproduce:

* in `DatabaseTests.cs`, add the two following tests `Test1` and `Test2`
```csharp

        [Fact]
        public virtual void Test1()
        {
            Assert.Equal(0, Context.Products.Count());
            Context.Products.Add(new Product {Name = "Foo"});
            Context.SaveChanges();
        }

        [Fact]
        public virtual void Test2()
        {
            Assert.Equal(0, Context.Products.Count());
            Context.Products.Add(new Product {Name = "Foo"});
            Context.SaveChanges();
        }
```
* run both tests (not each one individually, but select those two tests and run them)

**Expected result**: the two tests **should pass**
**Actual result**: one test **passes**, the other one **fails**
```
Assert.Equal() Failure
Expected: 0
Actual:   1
```

**Comment by Giorgi** [comment]
Yes, I didn't need the context to be cleared between tests because every call to `SaveChanges` throws with an exception so there was no record saved to the database. If that's not the case any more obviously this test will fail. Is that an issue ?

**Comment by Aerion** [comment]
That's an issue for the new tests added in #15, as they need to have data first saved before checking if an exception is thrown on the second SaveChanges is called. The products names/IDs were specifically chosen to be different than the ones already specified in the tests, so it's not really a problem right now, but something to keep in mind. If in those tests a `GD` product name was chosen and inserted, it could make other tests fail because of the name unicity.

**Comment by Giorgi** [comment]
@Aerion This is fixed now. I removed the two tests that you added.
