### ISSUE TITLE
Release new Nuget Sqlite version

### ISSUE THREAD

**Issue by Aerion** [Giorgi/EntityFramework.Exceptions#18]
Hello,

https://github.com/Giorgi/EntityFramework.Exceptions/pull/14 was merged on master April 12th and the last release of the [nuget package](https://www.nuget.org/packages/EntityFrameworkCore.Exceptions.Sqlite/) is from April 9th.
Could you release a new nuget version of the package so that this change is taken into account?

Thanks!

**Comment by Giorgi** [comment]
New package published on NuGet: [https://www.nuget.org/packages/EntityFrameworkCore.Exceptions.Sqlite/3.1.3](https://www.nuget.org/packages/EntityFrameworkCore.Exceptions.Sqlite/3.1.3)
