### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by sajidali2444** [Giorgi/EntityFramework.Exceptions#24]
@Giorgi 
Hi, Thank you for your hard work.
unfortunately, this is working for me.
I am using .net core 3.1 with MySql
could you please help to use this package. 
I have installed these package along with your package.
EntityFrameworkCore.Exceptions.MySql
EntityFrameworkCore.Exceptions.MySql.Pomelo
but it not working.
one more important thing I am customizing identity classes that why I am using DB context like this way
public class ApplicationDbContext: IdentityDbContext<ApplicationUser, ApplicationRole, int>
    {
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseExceptionProcessor();
        }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new PhotoConfiguration());
            modelBuilder.ApplyConfiguration(new XERideServicesConfiguration());
            modelBuilder.ApplyConfiguration(new XERideServicesSettingsConfiguration());
            modelBuilder.ApplyConfiguration(new RideRequestConfiguration());
            modelBuilder.ApplyConfiguration(new RideRequestDetailConfiguration());
            modelBuilder.ApplyConfiguration(new ComplainsConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationUserConfiguration());
            modelBuilder.ApplyConfiguration(new NotificationConfiguration());
            modelBuilder.ApplyConfiguration(new NotificationDetailConfiguration());
            modelBuilder.ApplyConfiguration(new FileConfiguration());
            modelBuilder.ApplyConfiguration(new BaseFaresConfiguration());
            base.OnModelCreating(modelBuilder);
        }

        public override int SaveChanges()
        {
            this.AuditEntities();
            return base.SaveChanges();
        }

        
        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            this.AuditEntities();

            return await base.SaveChangesAsync(cancellationToken);
        }
    }

**Comment by Giorgi** [comment]
Did you have a look at the [tests project](https://github.com/Giorgi/EntityFramework.Exceptions/tree/master/EntityFramework.Exceptions.Tests) ? It shows how it needs to be configured for MySql

**Comment by Giorgi** [comment]
Closing due to no response.
