### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by makingbloke** [Giorgi/EntityFramework.Exceptions#26]
Is there any plans for Oracle support?

**Comment by Giorgi** [comment]
Is there any interest in Oracle support?

**Comment by makingbloke** [comment]
Yes, exactly :) We develop a product that is cross database and Oracle support would be a very useful thing to have in the future.

**Comment by Giorgi** [comment]
You are free to contribute Oracle support 🙂

**Comment by anoordover** [comment]
I didn't see that there is interest in an Oracle implementation... I just issued a PR with the Oracle.ManagedDataAccess.Core version that is currently supported by Oracle.EntityFrameworkCore 3.19.8 (released 2 months ago)

**Comment by Giorgi** [comment]
Fixed by #27
