### ISSUE TITLE
EF Core 5.0 support

### ISSUE THREAD

**Issue by FabienDehopre** [Giorgi/EntityFramework.Exceptions#30]
Do you plan to support EF Core 5 which was release a couple of weeks ago?

**Comment by Giorgi** [comment]
It should already be compatible with EF 5. Do you have any issues using it with EF 5?

**Comment by FabienDehopre** [comment]
Indeed, it works with .NET 5.0
Maybe it would be a good idea to add that in the nuget manifest so it also appear in the package manager?

**Comment by Giorgi** [comment]
@FabienDehopre Can you clarify which manifest the library is missing? The `TargetFramework` in all projects is `netstandard2.0` and netstandard2.0 is compatible with .NET 5.0

**Comment by FabienDehopre** [comment]
Ah! Ok. I wasn't sure this was the case. But then, nothing needs to be made.
