### ISSUE TITLE
Add InMemory Support to enable testing

### ISSUE THREAD

**Issue by radderz** [Giorgi/EntityFramework.Exceptions#34]
Would it be possible to get these same generalized exceptions using the "InMemory" efcore option?

**Comment by Giorgi** [comment]
@radderz Does the in-memory provider throw exception for validations that fail (such as length, unique, and so on). If the does it might be possible to get the same exceptions but I think it doesn't. It definitely doesn't validate requiredness but it will be added in EF Core 6: https://github.com/dotnet/efcore/issues/10613

**Comment by radderz** [comment]
I see that the in memory database isn't a relation database which is not what I expected, I can probably use an in memory sqlite instance to do the same and you already have an sqlite version.

**Comment by Giorgi** [comment]
Yes, in-memory SQLite is probably a better choice for testing.
