### ISSUE TITLE
Cannot use extension optionsBuilder.UseExceptionProcessor()

### ISSUE THREAD

**Issue by petrformanek** [Giorgi/EntityFramework.Exceptions#38]
Hello,
I wanted to use `EntityFrameworkCore.Exceptions.SqlServer` package version `3.1.4` in my project but the extension method `optionsBuilder.UseExceptionProcessor()` cannot be used when using entity framework in more advanced way.

I'm configuring EF with [UseInternalServiceProvider(IServiceProvider)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.useinternalserviceprovider?view=efcore-5.0#microsoft-entityframeworkcore-dbcontextoptionsbuilder-useinternalserviceprovider(system-iserviceprovider)).

In this case the `self.ReplaceService<IStateManager, SqlServerExceptionProcessorStateManager>()` cannot be used, but I need to register it to service collection as scoped service like `services.AddScoped<IStateManager, SqlServerExceptionProcessorStateManager>()`.

The problem is that there is no extension method to do it and the `SqlServerExceptionProcessorStateManager` is not public.

Could you either make `SqlServerExceptionProcessorStateManager` public or provide some extension method?
For example [OracleExceptionProcessorStateManager](https://github.com/Giorgi/EntityFramework.Exceptions/blob/main/EntityFramework.Exceptions.Oracle/OracleExceptionProcessorStateManager.cs) is already public.

Thank you and have a great day!

**Comment by Giorgi** [comment]
@petrformanek I think it makes sense to create an extension method instead of making the classes public. Do you want to send a PR for it?

**Comment by petrformanek** [comment]
@Giorgi I can make a PR for it.

**Comment by petrformanek** [comment]
PR - https://github.com/Giorgi/EntityFramework.Exceptions/pull/39

**Comment by petrformanek** [comment]
> PR - #39

@Giorgi do you have any estimation when are you going to check and approve the PR #39?

**Comment by Giorgi** [comment]
@petrformanek Can you implement it for all supported databases?

**Comment by petrformanek** [comment]
@Giorgi, I'm sorry but my boss won't give me time to add it to all of them.

**Comment by Giorgi** [comment]
@petrformanek Why should I work for your boss for free?

**Comment by petrformanek** [comment]
@Giorgi and what is a problem with original PR? Why it was not merged?

**Comment by Giorgi** [comment]
It was implemented only for one database.
