### ISSUE TITLE
SaveChangesAsync

### ISSUE THREAD

**Issue by sb89** [Giorgi/EntityFramework.Exceptions#4]
So after trying out this package and looking at the code, this doesn't work for SaveChangeAsync right? Would it take much work to add this?

**Comment by Giorgi** [comment]
You are right, it doesn't work for `SaveChangeAsync` but it is easy to add support for it. All you have to do is override `SaveChangeAsync` in `ExceptionProcessorStateManager` the same way it is overriden for `SaveChanges`. Can you send a PR ?

**Comment by sb89** [comment]
Thanks for merging this. Would you be able to update the package on nuget?

**Comment by Giorgi** [comment]
I will update it on Monday

**Comment by Giorgi** [comment]
New nuget packages published
