### ISSUE TITLE
Support for the CosmosDB provider

### ISSUE THREAD

**Issue by julealgon** [Giorgi/EntityFramework.Exceptions#40]
Is there any work regarding a version of this library for the CosmosDB provider?

I ran into a situation today where I needed to handled the `DbUpdateException` and after some searching, found out about this library. However, I'm using the Cosmos provider, which doesn't appear to be supported at the moment.

**Comment by Giorgi** [comment]
As you noted the library doesn't support CosmosDB but if you want to contribute you are more than welcome.
