### ISSUE TITLE
How can one use UseExceptionProcessor in code targetting multiple databases?

### ISSUE THREAD

**Issue by derek-mba** [Giorgi/EntityFramework.Exceptions#43]
In Startup.cs I have

            if (isPostGres)
            {
                services.AddDbContext<CprDbContext>(options => options
                    .UseNpgsql(connection, x => x.UseNetTopologySuite())
                    .UseExceptionProcessor(options);
                );
            }
            else
            {
                services.AddDbContext<CprDbContext>(options => options
                    .UseSqlServer(connection, x => x.UseNetTopologySuite())
                    .UseExceptionProcessor(options)
                    );
            }

Obviously, this gives:
```
The call is ambiguous between the following methods or properties: 'EntityFramework.Exceptions.PostgreSQL.ExceptionProcessorExtensions.UseExceptionProcessor(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)' and 'EntityFramework.Exceptions.SqlServer.ExceptionProcessorExtensions.UseExceptionProcessor(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)' 
```

I could use `AddInterceptors()` rather than `UseExceptionProcessor()` if the interceptors were public, but since they aren't, how can I manage to accomplish this for a database determined purely by its connection string?

**Comment by Giorgi** [comment]
You can call `UseExceptionProcessor` as a static method.

**Comment by derek-mba** [comment]
Oh, of course. Sorry!
