### ISSUE TITLE
Strong-named assembly

### ISSUE THREAD

**Issue by petarpetrovt** [Giorgi/EntityFramework.Exceptions#47]
> Warning	CS8002	Referenced assembly 'EntityFramework.Exceptions.SqlServer, Version=6.0.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
> Warning	CS8002	Referenced assembly 'EntityFramework.Exceptions.Common, Version=6.0.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

* [Strong-named assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named)
* [strong-name-signing](https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md)

**Comment by Giorgi** [comment]
According to [Why strong-name your assemblies?](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)

> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

This library targets .Net 6 so there is no sense in strong naming the assemblies.
