### ISSUE TITLE
[Question] how to suppress log messages from EF-Core 

### ISSUE THREAD

**Issue by AplixaMartinMetzler** [Giorgi/EntityFramework.Exceptions#48]
Hi Giorgi,

first of all, thanks for your work, i really like this lib. 

Its just a side question which i guess is more concern of ef-core, anyway:

Im working with postgres and i have this usecase:
```

    try
        {
            dbContext.SaveChanges();
        }

        catch (UniqueConstraintException)
        {
            //.... resolve task
            dbContext.SaveChanges();
        }
```

At the moment of the catch clause EF-Core already has written already a log message:
```
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type
```

Is there any possbility to supress this kind of messages?

**Comment by AplixaMartinMetzler** [comment]
Ok, thanks for fast response. I will try that.

**Comment by Matthew-Bright** [comment]
Hi @Giorgi

I am also seeing the "Failed executing DbCommand ..." being logged by entity framework. Would you happen to know what the EventId is for that message so that I can suppress it?

Thanks

-- Matthew

**Comment by Giorgi** [comment]
@Matthew-Bright `CoreEventId.SaveChangesFailed` is the eventId not to log any error when `SaveChanges` is called
