### ISSUE TITLE
MaxLengthExceededException not being thrown when using SQL Server 2019

### ISSUE THREAD

**Issue by johnavery** [Giorgi/EntityFramework.Exceptions#52]
Hello, I just integrated your library into my code, and to test, I attempted to produce a MaxLengthExceededException by setting a 32 character field to 33 characters.  To my surprise, instead of catching a MaxLengthExceededException, I instead caught a plain-old DbUpdateException.

I viewed the code in SqlServerExceptionProcessorInterceptor, and I see that you are matching that exception up with error 8152, but for SQL Server 2019, that error code has been replaced by 2628 (see: [String or Binary data would be truncated: replacing the infamous error 8152](https://docs.microsoft.com/en-us/archive/blogs/sql_server_team/string-or-binary-data-would-be-truncated-replacing-the-infamous-error-8152)).

Can you please update the package such that it would treat either code as a MaxLengthExceededException?  For now I can workaround by inspecting the error number manually.  Thanks!

**Comment by Giorgi** [comment]
@johnavery Thanks for bringing this to my attention. Do you want to create a PR as well for this issue? Should be straightforward to add this.

**Comment by johnavery** [comment]
All set.

**Comment by Giorgi** [comment]
Thanks, I'll publish a new version tomorrow.

**Comment by Giorgi** [comment]
@johnavery New version published on NuGet
