### ISSUE TITLE
PooledDbContext

### ISSUE THREAD

**Issue by FoxTes** [Giorgi/EntityFramework.Exceptions#56]
Hello.

I ran into the problem of adding this library when using a context pool.

Registration:

```
builder.Services.AddPooledDbContextFactory<ApplicationContext>(options => options.UseNpgsql(connectionString));

public class ApplicationContext : DbContext
{
    public ApplicationContext(DbContextOptions<ApplicationContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseExceptionProcessor();
    }
}
```

Error:
`Unhandled exception. System.InvalidOperationException: 'OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled.`

**Comment by Giorgi** [comment]
The library works perfectly with DbContext pooling. Either read the documentation for [DbContext pooling](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=without-di%2Cwith-constant#dbcontext-pooling) or [Sponsor the Project](https://github.com/sponsors/Giorgi) and I'll provide an example.

**Comment by FoxTes** [comment]
Well, I didn't expect such an answer.
You are making an open source library. Don't you think that this instruction should be added to the readme so that people know how to use it? And not to demand money from them.

**Comment by Giorgi** [comment]
Your question isn't specific to this library, it can be rephrased as _How do I configure DbContext when using DbContext pooling?_
