### ISSUE TITLE
Trusted certificate issue when package installed but not used

### ISSUE THREAD

**Issue by rer145** [Giorgi/EntityFramework.Exceptions#58]
Once I installed the package (SqlServer) to my .NET 6 API project and added the call to `UseExceptionProcessor()` when configuring my DbContext, I ran into an issue with my connection, saying:

> A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)

Adding the `TrustServerCertificate=True` to my connection string solved the issue.

However, when I commented out the `UseExceptionProcessor()` call and removed the `TrustServerCertificate=True` portion from the connection string, the error still occurred.

Only once I uninstalled the package from the project did it resolve itself. What all is the package doing when installed but not setup to run? Shouldn't it not be doing anything differently?

**Comment by Giorgi** [comment]
This looks related to https://github.com/Giorgi/EntityFramework.Exceptions/issues/49. Installing the `EntityFrameworkCore.Exceptions.SqlServer` package increases ` Microsoft.Data.SqlClient` version to 4 that has some breaking changes about Sql Server connection encryption behavior.

**Comment by rer145** [comment]
My apologies, I did not see that one in my (admittedly) quick search.
