### ISSUE TITLE
ExceptionProcessorContext?

### ISSUE THREAD

**Issue by michellesong2** [Giorgi/EntityFramework.Exceptions#6]
I downloade the SqlServer package but cannot find the ExceptionProcessorContext. This class is missing in the EntityFramework.Exceptions.Common.

**Comment by Giorgi** [comment]
In the latest version of the library you don't need to use `ExceptionProcessorContext`. Just call `UseExceptionProcessor` in `OnConfiguring` method: [How do I get started](https://github.com/Giorgi/EntityFramework.Exceptions#how-do-i-get-started)
