### ISSUE TITLE
What's the corresponding Exception in this framework for Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException

### ISSUE THREAD

**Issue by haroldrandom** [Giorgi/EntityFramework.Exceptions#66]
As title.

Is there any you-defined exception for this exception `Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException`?

**Comment by Giorgi** [comment]
No, there is no other exception because `DbUpdateConcurrencyException` already gives you the reason why the statement failed.
