### ISSUE TITLE
8.0.0.1 Nuget package compilation issue

### ISSUE THREAD

**Issue by joedirt** [Giorgi/EntityFramework.Exceptions#68]
There appears to be a packaging issue with the latest nuget release 8.0.0.1:  The names of the DLL and PDB files are not correct

After running a nuget update, many tests started to fail with the message: 
![image](https://github.com/Giorgi/EntityFramework.Exceptions/assets/190430/106c1d7e-d055-47fd-88d5-5d2fff829587)

I looked through the downloaded package and saw the following, which appears to be incorrectly named files:

![image](https://github.com/Giorgi/EntityFramework.Exceptions/assets/190430/310a13bb-3389-47a8-89f9-677d5ce3916a)

I then looked in my VS dependency list and see this:

![image](https://github.com/Giorgi/EntityFramework.Exceptions/assets/190430/2aca9b09-3495-4839-b9ae-251393a45735)

**Comment by Giorgi** [comment]
Which package do you have in your project?

**Comment by joedirt** [comment]
EntityFrameworkCore.Exceptions.Common (8.0.0.1) - https://www.nuget.org/packages/EntityFrameworkCore.Exceptions.Common

**Comment by Giorgi** [comment]
You shouldn't reference that package directly. You should reference a database specific top level package.

**Comment by joedirt** [comment]
Thanks.  I've removed the package and only include the Oracle one.  The tests all pass.

Question:  is the missing package name from the DLL and PDB still something you want to look at, or is it by design?

**Comment by Giorgi** [comment]
That's weird. It should not be like that.

**Comment by Giorgi** [comment]
I uploaded `8.0.0.2` and unlisted `8.0.0.1`
