### ISSUE TITLE
Duplicate sqlite dll on build

### ISSUE THREAD

**Issue by alex6dj** [Giorgi/EntityFramework.Exceptions#72]
Hi Im creating a new project and want to use this library. Im trying to use a password protected SQlite DB. For this I should reference `microsoft.entityframeworkcore.sqlite.core` because it dont have an sqlite dll embeded and use `sqlitepclraw.bundle_e_sqlcipher` wich support encrypted DB.

The issue is that `EntityFramework.Exceptions` have an internal dependency in `microsoft.data.sqlite` without `core` and the result build contains both sqlite versions.

The result buid:
With `EntityFramework.Exceptions` contains `e_sqlcipher.dll` and `e_sqlite3.dll`
![image](https://github.com/Giorgi/EntityFramework.Exceptions/assets/27690651/482b034d-ead5-4971-bee9-35ae883bf4a8)

Without `EntityFramework.Exceptions`, only `e_sqlcipher.dll`
![image](https://github.com/Giorgi/EntityFramework.Exceptions/assets/27690651/014a36f3-8aa1-4ab6-84c7-a96a7cf8ff21)

Any workaround is welcome.

Thanks in advance.

**Comment by Giorgi** [comment]
Is simply deleting `e_sqlite3.dll` from the bin directory enough? If yes you could add a post build step as a workaround.

**Comment by alex6dj** [comment]
I, sorry for the late answer. I check and droping e_sqlite3.dll manually solve the problem and some basic testing shows the app only using the e_sqlcipher.dll. Is yet to test if trimming remove the unneeded dll or not. Just need to find a way to remove before single file generation.

**Comment by Giorgi** [comment]
@alex6dj Is this still an issue?

**Comment by alex6dj** [comment]
Hello. Yes, I still think it is a problem yet. Not directly now, but in the future. For now I am removing the extra dlls using the command I published in the previous post, but in the long run the idea is to publish the app using NativeAOT and by not removing the dlls it will increase the final size of the application unnecessarily. Apart from this, by eliminating the unnecessary dlls the application works correctly.

**Comment by Giorgi** [comment]
I added a new package `https://www.nuget.org/packages/EntityFrameworkCore.Exceptions.Sqlite.Core` that depends on `Microsoft.Data.Sqlite.Core` instead of `Microsoft.Data.Sqlite`
