### ISSUE TITLE
Duplicate foreign key name

### ISSUE THREAD

**Issue by Giorgi** [Giorgi/EntityFramework.Exceptions#76]
@Giorgi https://github.com/Eric-Ans/TestEntityFrameworkExceptions

This sample throw the error I describe previously when context.SaveChanges(); is called in main.

If you look at file : 20240731133414_InitialCreate.Designer.cs: you will see two entries with the same foreign key name : HasConstraintName("fk_montants_pieces_piece_id");

and in ExceptionProcessorInterceptor class line 118, mappedConstraints contains the same two constraint name, so ToDictionary fail.

![image](https://github.com/user-attachments/assets/71064055-14e2-404f-b1cf-4fc9a5799ba9)

![image](https://github.com/user-attachments/assets/321e2d35-ebdf-42e0-8420-bd30b6d9c3b2)

_Originally posted by @Eric-Ans in https://github.com/Giorgi/EntityFramework.Exceptions/issues/71#issuecomment-2260585140_

**Comment by Eric-Ans** [comment]
@Giorgi Thank you very much :) could you publish a nuget package ?

**Comment by Giorgi** [comment]
I'll, once I merge the open PR

**Comment by Giorgi** [comment]
Pushed.
