### ISSUE TITLE
Add reference constraint support for sql server 

### ISSUE THREAD

**Issue by kaiserjpg** [Giorgi/EntityFramework.Exceptions#8]
It would be nice to add support for error 547 in sql server which is a reference constraint error. I created a pull request for you to review the new feature and if approved update the nuget package.

**Comment by Giorgi** [comment]
Thanks for the PR. Do you know if there is a similar error in other database engines so that we can support it in all packages ?

**Comment by kaiserjpg** [comment]
I saw the latest list of errors in mysql [here](https://dev.mysql.com/doc/refman/5.5/en/server-error-reference.html) 
Not sure how accurate it is, since I saw that you use 1062 for DuplicateEntryForKey (Unique constraint) but here the code is 1169. This might be related to the DB version.

For PostgreSQL you can find the latest list (v 9.4) [here ](https://www.postgresql.org/docs/9.4/errcodes-appendix.html). Keep in mind that PostgreSQL uses two codes for this validation: 
![image](https://user-images.githubusercontent.com/19473847/66529983-e8b14f00-eac2-11e9-895b-df763cc1337f.png)

**Comment by Giorgi** [comment]
Merged.

**Comment by Giorgi** [comment]
@kaiserjpg I added support for ReferenceConstraintException for other databases too
